### ISSUE TITLE
Getting CORS Error

### ISSUE THREAD

**Issue by AasthaSethia** [sdoxsee/examples#1]
After integrating with my front end app I am getting CORS issue as my pre-flight request is giving me 403

**Comment by sdoxsee** [comment]
I'm guessing that's because you need to combine your existing HttpSecurity that handles cors with the one I provided. After adding this one, your old is probably overridden?

**Comment by AasthaSethia** [comment]
I did not have any existing httpsecurity I added annotations @crossorigin but that isnt working I added a cors registru bean that isn't working either

**Comment by sdoxsee** [comment]
Fair enough but I can't really help without more information

**Comment by AasthaSethia** [comment]
@Override
    protected void configure(HttpSecurity http) throws Exception
    {
        super.configure(http);
        http.cors().and().authorizeRequests().antMatchers("/hello").permitAll();
        http.csrf().disable();
    }
I add this method and it shows cannot have antmatchers after anyRequest

**Comment by sdoxsee** [comment]
Closing because this is not an issue with the my example code and I haven't been provided with a sample repo to reproduce the error for @AasthaSethia's specific situation. If you you're looking for support, please post on stackoverflow and leave a comment on the blog post (https://sdoxsee.github.io/blog/2021/03/22/multi-tenant-oauth-2.0-resource-servers) where others can assist as well. Regards
